# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [198]:

import numpy as np
import pandas as pd

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [199]:
 a = pd.Series([100,200,300,400])

Print a, and data type

In [200]:

print(a)
print(a.dtype)

0    100
1    200
2    300
3    400
dtype: int64
int64

Using indexing access the element 300 from the series a.

In [201]:
print(a.iloc[2])

300

What are the values of index for series a?

In [202]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [203]:

a = pd.Series([100,200,300,400],
index=['c','a','b','d'])
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [204]:
print(a['d'])

400

Sort the values wrt to the index and print it

In [205]:

print(a.sort_index())

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [206]:
b = pd.Series([800,450,100],index=['e','f','g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [207]:
 a =pd.concat([a,b])

In [208]:
#print a again after appending b into it

print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [209]:
 a = a.sort_values(ascending=False)
 print(a.index)

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [210]:
 df = pd.DataFrame(a)

In [211]:
print(df)

     0
e  800
f  450
d  400
b  300
a  200
c  100
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [212]:
print(df.shape)

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [213]:
# yep its same as the series.
print(a.index)

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [214]:
print(df.head())

     0
e  800
f  450
d  400
b  300
a  200

In [215]:

print(a.tail())

d    400
b    300
a    200
c    100
g    100
dtype: int64

Rename the column of the dataframe as 'points'

In [216]:


df.columns = ['points']
print(df)

   points
e     800
f     450
d     400
b     300
a     200
c     100
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [217]:
#Create fruits array

fruits = pd.Series(np.random.choice(['orange','mango','apple'],size=len(df)),index = df.index)

print(fruits)

e     mango
f    orange
d    orange
b     apple
a    orange
c     apple
g     mango
dtype: object

In [218]:
#Create series fruits out of fruits array
fruits = pd.Series(fruits)
print(fruits)

e     mango
f    orange
d    orange
b     apple
a    orange
c     apple
g     mango
dtype: object

Change the index of fruits to the index of dataframe df

In [219]:

fruits.index = df.index
print(fruits)

e     mango
f    orange
d    orange
b     apple
a    orange
c     apple
g     mango
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [220]:

df['fruits'] = fruits
print(df)

   points  fruits
e     800   mango
f     450  orange
d     400  orange
b     300   apple
a     200  orange
c     100   apple
g     100   mango

In [221]:
print(df.head())

   points  fruits
e     800   mango
f     450  orange
d     400  orange
b     300   apple
a     200  orange

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [222]:
d1 = pd.DataFrame({'city':['Chandigarh','Delhi','Kanpur','Chennai','Manali'],
                   'Temperature': [15,22,20,26,-2]})

Print(d1)

In [223]:

print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [224]:

print(d1.shape)

(5, 2)

Set city = d1['city']

In [225]:

city=d1['city']

print city <br>
What is the type of city.

In [226]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [227]:
d2 = pd.DataFrame({'city':['Bengalaru','Coimbatore','Srirangam','Pondicherry'],
                    'Temprature':[24,35,36,39]})
print(d2)

          city  Temprature
0    Bengalaru          24
1   Coimbatore          35
2    Srirangam          36
3  Pondicherry          39

print the shape of this dataframe

In [228]:
print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [229]:
d3 = pd.concat([d1,d2])
print(d3)

          city  Temperature  Temprature
0   Chandigarh         15.0         NaN
1        Delhi         22.0         NaN
2       Kanpur         20.0         NaN
3      Chennai         26.0         NaN
4       Manali         -2.0         NaN
0    Bengalaru          NaN        24.0
1   Coimbatore          NaN        35.0
2    Srirangam          NaN        36.0
3  Pondicherry          NaN        39.0

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [230]:
cold_cities = d3[d3['Temperature']<=20]
print(cold_cities)
print('Total Cities:',len(cold_cities))

         city  Temperature  Temprature
0  Chandigarh         15.0         NaN
2      Kanpur         20.0         NaN
4      Manali         -2.0         NaN
Total Cities: 3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [231]:


hot_cities=d3[d3['Temperature']>=35]
print(hot_cities)
print('Total Cities:',len(hot_cities))

Empty DataFrame
Columns: [city, Temperature, Temprature]
Index: []
Total Cities: 0

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not. 
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [232]:
# write function here

def is_union_territory(city):
    ut_list = ['Chandigarh','Pondicherry','Delhi']
    if city in ut_list:
        return True
    else:
        return False
    
#     # write code below
    
d3['is_ut'] = d3['city'].apply(is_union_territory)

In [233]:
print(d3)

          city  Temperature  Temprature  is_ut
0   Chandigarh         15.0         NaN   True
1        Delhi         22.0         NaN   True
2       Kanpur         20.0         NaN  False
3      Chennai         26.0         NaN  False
4       Manali         -2.0         NaN  False
0    Bengalaru          NaN        24.0  False
1   Coimbatore          NaN        35.0  False
2    Srirangam          NaN        36.0  False
3  Pondicherry          NaN        39.0   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT - 
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [234]:
def c_to_f(c):
    return(c*9/5)+32
# check function c_to_f(10)
print(c_to_f(10))
d3['Temp_F'] = d3['Temperature'].apply(c_to_f)
print(d3)

50.0
          city  Temperature  Temprature  is_ut  Temp_F
0   Chandigarh         15.0         NaN   True    59.0
1        Delhi         22.0         NaN   True    71.6
2       Kanpur         20.0         NaN  False    68.0
3      Chennai         26.0         NaN  False    78.8
4       Manali         -2.0         NaN  False    28.4
0    Bengalaru          NaN        24.0  False     NaN
1   Coimbatore          NaN        35.0  False     NaN
2    Srirangam          NaN        36.0  False     NaN
3  Pondicherry          NaN        39.0   True     NaN

In [235]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'
d3['temp_farenhiet']=d3['Temperature'].apply(c_to_f)
print(d3)

          city  Temperature  Temprature  is_ut  Temp_F  temp_farenhiet
0   Chandigarh         15.0         NaN   True    59.0            59.0
1        Delhi         22.0         NaN   True    71.6            71.6
2       Kanpur         20.0         NaN  False    68.0            68.0
3      Chennai         26.0         NaN  False    78.8            78.8
4       Manali         -2.0         NaN  False    28.4            28.4
0    Bengalaru          NaN        24.0  False     NaN             NaN
1   Coimbatore          NaN        35.0  False     NaN             NaN
2    Srirangam          NaN        36.0  False     NaN             NaN
3  Pondicherry          NaN        39.0   True     NaN             NaN

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [236]:
ut_cities_d1 = d1[d1['city'].isin(['Chandigarh','Delhi','Pondicherry','Puducherry'])]
print(ut_cities_d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [237]:

d1[d1['Temperature'].apply(lambda c: (c*9/5)+32)>90]

Empty DataFrame
Columns: [city, Temperature]
Index: []

Select only the first three rows of the dataframe d1.

In [238]:
d1.head(3)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [239]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

## Groupby

In [240]:
# Create a dataframe using dictionary of your choice

data = {'Name':['Ram','Kajal','Rahul','Geeta','Ravi'],
         'age': [23,18,21,19,20],
         'Marks':[46,76,65,87,79]}
df=pd.DataFrame(data)
df

    Name  age  Marks
0    Ram   23     46
1  Kajal   18     76
2  Rahul   21     65
3  Geeta   19     87
4   Ravi   20     79

In [241]:
# Use Groupby of single column with aggregate sum()

df.groupby('age')['Marks'].sum()

age
18    76
19    87
20    79
21    65
23    46
Name: Marks, dtype: int64

In [242]:
# Use Groupby of single column with aggregate count()

df.groupby('Name')['age'].count()

Name
Geeta    1
Kajal    1
Rahul    1
Ram      1
Ravi     1
Name: age, dtype: int64

In [243]:
# Use Groupby of single column with aggregate min() and max()
df.groupby('Name')['age'].min()
df.groupby('Name')['age'].max()

Name
Geeta    19
Kajal    18
Rahul    21
Ram      23
Ravi     20
Name: age, dtype: int64

In [244]:
# Use Groupby of any 2 columns with aggregate mean()

df.groupby(['Name','age'])['Marks'].mean()

Name   age
Geeta  19     87.0
Kajal  18     76.0
Rahul  21     65.0
Ram    23     46.0
Ravi   20     79.0
Name: Marks, dtype: float64

In [245]:
# Use Groupby of any 2 columns with aggregate min() and max()

df.groupby(['Name','age'])['Marks'].min()
df.groupby(['Name','age'])['Marks'].max()

Name   age
Geeta  19     87
Kajal  18     76
Rahul  21     65
Ram    23     46
Ravi   20     79
Name: Marks, dtype: int64

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [246]:
a =pd.date_range(start='2020-01-01',end='2021-04-01')

print a

In [247]:
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [248]:
print(len(a))

457

What is the type of a?

In [249]:

print(type(a))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>